name: Quality Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Check formatting (black)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Security scan (bandit)
        run: bandit -r src/ -c pyproject.toml

      - name: Dead code analysis (vulture)
        run: vulture .
        continue-on-error: true

      - name: Run tests (pytest)
        run: pytest tests/ --tb=short
